### PR TITLE
Avoid precision errors in TSR

### PR DESCRIPTION
**Pull request by davidisaaclee**
I'm using the TSR estimator for multitouch gestures that can be arbitrary number of points (something like `estimate('tsr', touchesBefore.map(clientPosition), touchesAfter.map(clientPosition))`). When doing this with some single-touch point sets, I found that the resulting transform had `a === b === 0` – confusing because a single pointer pan should always be a valid translation, no?

I looked into it – it looks like the specific points I was providing were causing a precision error when calculating `det`. Here's a test that fails on current `master`: https://github.com/davidisaaclee/nudged/blob/2594af5c79660ef805f8892b20c135151faf03e7/test/estimators/TSR.test.js#L100-L111

Some other valid solutions:
- I could round my inputs to more reasonable precisions
- I could switch to `T` estimator when I know I have one point

But I'd prefer not to think about that stuff! so here's a PR that fixes this by just switching the order of `det` expression so that the terms that probably will cancel each other out are next to each other. I don't fully get why it works, but it makes the test pass.

Thanks for the great library, I use it in almost every web app I make.

### CODE REVIEW

**Comment by axelpale** [comment]
Hi David! Thanks for the contribution. I am so sorry it has taken so long to clear up my queue of tasks in order to dive into this one.

Good catch. Those floating-point near-zero issues are always surprising and annoying to deal with, especially outside of the library. I need to inspect the code a bit more to discover the root cause and also check if the same happens with other estimators. I wish to be able to merge this in nudged 2.0.1 or 2.1.0.

**Comment by axelpale** [comment]
Merged. Thanks again. I will do some further numerical analysis on this, although your notion that now the terms cancel each other is probably exactly what is happening and the perfect solution to the numerical issue. I will also ensure that TSR resolves one-point cases always with translation only.
⭐⭐⭐⭐⭐

**Comment by axelpale** [comment]
Done. This PR also helped in taking the same robustness improvements to R, TS and TR estimators. Excellent quality improvement!

**Comment by davidisaaclee** [comment]
:) glad to hear it! thanks again for the library.

**Comment by axelpale** [comment]
Just wanted to let you know this was released today in nudged v2.0.1. Cheers!

**Pull request merged**
