### PR TITLE
Add nudged.createFromString

### PR DESCRIPTION
**Pull request by wysman**
Hi,

I have write a function to create a transform object from a CSS String for my personal usage but i think it's can be usefull for others.

Related to #21 

Best regards,

### CODE REVIEW

**Comment by wysman** [comment]
Here a usage exemple

```
var t = nudged.createFromString('scale(1) translate(-669872.529, -6860259.837) rotate(-3.483)')
console.log(t)
console.log(t.transform([669872.529, 6860259.837]))
console.log(t.transform([669892.47, 6860261.05]))
console.log(t.transform([669871.31, 6860279.84]))
console.log(t.transform([669891.25, 6860281.05]))

```

**Comment by axelpale** [comment]
Thank you! Nice feature and will definitely fix #21.

I would like to hear more about your use case. It could be valuable for documentation, further design, and provide readers some context why the method exists.

Also, may I ask your insight on why did you choose `createFromString` instead of `createFromCssTransform` or something more accurate? It felt simpler? Or did you envision the method to support some other string formats in the future? Formally, I think, the most accurate term might be [transform-list](https://developer.mozilla.org/en-US/docs/Web/CSS/transform).

Happy to hear your thoughts.

**Comment by wysman** [comment]
For our use case, we want to be able to retrieve human readable transformation from API. Then we use it to have local reference on open-layers maps.

We can rename the function `createFromCssTransform`, but i think the `createFromString` is simpler and more consistent with the `createFromArray` name. It's can be less confusing if we do not support all CSS keywords.

Today, i have implement a version which its fine for our use case. Adding more keyword is not hard if they are mapped to a `nudged.Transform` method.

Regards,

**Comment by axelpale** [comment]
This is awesome feature and I feel ashamed I haven't had time to look into it since May. I plan to merge it to nudged 2.0.0 because the array function expression and other ES6 syntax might break ES5 builds. I aim to convert the whole codebase to ES6 at nudged 2.0.0 and then I can merge your useful contribution and its nice syntax as-is.

**Pull request merged**
